console.warn("*** EXPRESIONES REGULARES");
console.warn("* Comunmente las expresiones regulares se encargan de buscar caracteres en especifico dentro de una cadena de texto");
console.warn("* Las expresiones regulares trabajan con KeySensitive, por lo tanto, distinguira de mayusculas y minusculas.");
console.warn("* ^ Significa que va a buscar en la primera posicion");
console.warn("* $ Significa que va a buscar en la ultima posicion");
console.warn("* . Retorna el primer caracter, si se colocan dos puntos(..) retornara dos caracteres, etc...");

var regexCadena1 = "Hola Mundo";
console.log("   Cadena para practica = " + regexCadena1);
console.log("   ");
console.info("* Al buscar un  caracter dentro de una cadena con al expresion /x/ retornara un array con el indice en donde encontro ese caracter.")
console.log("   Retorno con expresion /a/ = ", regexCadena1.match(/a/));
console.info("* Podremos acceder al indice mediante su posicion ['index']");
var arrayRegexC1 = regexCadena1.match(/a/);
console.log("   Retorno con expresion /a/ en su posición ['index'] = ", arrayRegexC1["index"]);
console.info("* ^ retornara la primer posicion si esta concuerda con el caracter escrito despues de este simbolo");
console.log("   Retorno con expresion /^H/ = ", regexCadena1.match(/^H/));
console.log("   Retorno con expresion /^o/ = ", regexCadena1.match(/^o/));
console.info("* . retornara caracteres desde la posicion 0, dependiendo el numero de puntos, sera los caracteres a retornar")
console.log("   Retorno con expresion /./ = ",regexCadena1.match(/./));
console.log("   Retorno con expresion /../ = ",regexCadena1.match(/../));
console.log("   Retorno con expresion /../ = ",regexCadena1.match(/.../));
console.info("* $ retornara la ultima posicion de la cadena si es que esta coincide con el caractera puesto antes del simbolo");
console.log("   Retorno con expresion /o$/ = ",regexCadena1.match(/o$/));
console.log("   Retorno con expresion /a$/ = ",regexCadena1.match(/a$/));
console.info("* Al juntar ^. estamos indicando que se regresara la letra en la primer posicion, si posterior al . colocamos un caracter, solo funcionara si este caracter se encuentra despues de la primer posicion");
console.log("   Retorno con expresion /^./ = ",regexCadena1.match(/^./));
console.log("   Retorno con expresion /^../ = ",regexCadena1.match(/^../));
console.log("   Retorno con expresion /^.o/ = ",regexCadena1.match(/^.o/));
console.info("* Al juntar .$ obtendremos el el ultimo digito de una cadena. Si ademas, se coloca una letra antes del punto, estaremos obteniendo el ultimo digito y la letra colocada en caso de coincidir");
console.log("   Retorno con expresion /.$/ = ",regexCadena1.match(/.$/));
console.log("   Retorno con expresion /d.$/ = ",regexCadena1.match(/d.$/));
console.log("   Retorno con expresion /..$/ = ",regexCadena1.match(/..$/));
console.info("* Al colocar expresiones entre corchetes se estara buscando en que posicion se encuentra ese caracter [abcA-Z], [146]");
console.info("  [a-z] buscara de la 'a' a la 'z' en todas las posiciones, si encuentra en la primer posicion retornara como indice el numero 0");
console.info("  [0-9] buscara del '0' al '9' en todas las posiciones, si encuentra en la primer posicion retornara como indice el numero 0");
console.log("   Retorno con expresion /[a-z]/ = ",regexCadena1.match(/[a-z]/));
console.log("   Retorno con expresion /[A-Z]/ = ",regexCadena1.match(/[A-Z]/));
console.info("* /^H[aou]/ nos retornara valor solo si la primer letra es una H y la siguiente coincide con a,o,u");
console.log("   Retorno con expresion /^H[aou]/ = ",regexCadena1.match(/^H[aou]/));
console.log("   Retorno con expresion /^H[aiu]/ = ",regexCadena1.match(/^H[aiu]/));
console.info("* /\\s/ nos retornara espacios dentro de pa cadena");
console.log("   Retorno con expresion /\\s/ = ",regexCadena1.match(/\s/));
console.log("   Retorno con expresion /\\w/ que buscara todas las letras por mayus y minus = ",regexCadena1.match(/\w/));
console.log("   Retorno con expresion /\\d/ que buscara todas numeros = ",regexCadena1.match(/\d/));
console.warn("* Controladores i, g y m");
console.log("   i, buscara la letra especificada ya sea mayuscula o minuscula");
console.log("   Retorno con expresion /[m]/ = ",regexCadena1.match(/[m]/));
console.log("   Retorno con expresion /[m]/i = ",regexCadena1.match(/[m]/i));
console.log("*  g, retornara todas las coincidencias encontradas en un array");
var regexCadena2 = "HolA Mundoo \nQué pasooo?";
console.log(regexCadena2);
console.log("   Retorno con expresion /[aeiou]/g = ",regexCadena2.match(/[aeiou]/g));
console.log("   Retorno con expresion /[aeiou]/gi = ",regexCadena2.match(/[aeiou]/gi));
console.log("   Retorno con expresion /[aeiou]|é/gi = ",regexCadena2.match(/[aeiou]|é/gi));
console.log("   Retorno con expresion /[aeiou]1[é]/gi = ",regexCadena2.match(/[aeiou]|[é]/gi));
console.log("*  +, nos ayudara a retornar caracteres repetidos en la misma posicion");
console.log("   Retorno con expresion /o+/g = ",regexCadena2.match(/o+/g));
console.log("*  ?, Retorna toda la cadena poniendo vacios en donde no coincida con la busqueda");
console.log("   Retorno con expresion /o?/g = ",regexCadena2.match(/o?/g));
console.log("   Retorno con expresion /o?/g = ",regexCadena2.match(/o?/g));
console.log("*  {x,y}, nos retornara una secuencia si es que cuenta con los caracteres mencionados")
console.log("   Retorno con expresion /o{2,3}/g = ",regexCadena2.match(/o{2,3}/g));
var regexCadena3 = "Hoy ganamos 3 partidas de 20 y quede en lugar 2";
console.log(regexCadena3, " extraer decimal con \\d = ", regexCadena3.match(/\d/));
console.log(regexCadena3, " extraer cada decimal con \\d y g = ", regexCadena3.match(/\d/g));
console.log(regexCadena3, " extraer cada conjunto de decimal con \\d, {x,y} y g = ", regexCadena3.match(/\d{1,}/g));
console.log(regexCadena3, " extraer cada conjunto de decimal con \\d, {x,y}, g y añadir palabra = ", regexCadena3.match(/\d{1,}|hoy/gi));
