create database practica2;
use practica2;

create table productos(
	ID_FAB CHAR(3) NOT NULL,
	ID_PRODUCTO CHAR(5) NOT NULL,
	DESCRIPCION VARCHAR(20) NOT NULL,
	PRECIO MONEY NOT NULL,
	EXISTENCIA INT NOT NULL

	CONSTRAINT PK_PROD_IDF_IDP PRIMARY KEY (ID_FAB, ID_PRODUCTO)
	);

create table clientes(
	NUM_CLIE INT NOT NULL,
	EMPRESA VARCHAR(20) NOT NULL,
	REP_CLIE INT,
	LIMITE_CR MONEY

	CONSTRAINT PK_CLI_NUMC PRIMARY KEY (NUM_CLIE)
	);

create table oficinas(
	OFICINA INT NOT NULL,
	CIUDAD VARCHAR(15) NOT NULL,
	REGION VARCHAR(10) NOT NULL,
	DIR INT,
	OBJETIVO MONEY,
	VENTAS MONEY NOT NULL

	CONSTRAINT PK_OFIC_OFIC PRIMARY KEY(OFICINA)
	);

create table pedidos(
	NUM_PEDIDOS INT NOT NULL,
	FECHA_PEDIDO DATE NOT NULL,
	CLIE INT NOT NULL,
	REP INT,
	FAB CHAR(3) NOT NULL,
	PRODUCTO CHAR(5) NOT NULL,
	CANT INT NOT NULL,
	IMPORTANTE MONEY NOT NULL

	CONSTRAINT PK_PEDI_NPED PRIMARY KEY(NUM_PEDIDOS),
	CONSTRAINT FK_CLI_PEDI_CLI FOREIGN KEY (CLIE) REFERENCES CLIENTES (NUM_CLIE),
	CONSTRAINT FK_PROD_PEDI_REPFAB FOREIGN KEY (FAB, PRODUCTO) REFERENCES PRODUCTOS (ID_FAB, ID_PRODUCTO)
	);

create table repventas(
	NUM_EMPL INT NOT NULL,
	NAME VARCHAR(15) NOT NULL,
	EDAD INT, OFICINA_R INT,
	TITULO VARCHAR(10),
	CONTRATO DATE NOT NULL,
	DIRECTOR INT, CUOTA MONEY,
	VENTAS MONEY NOT NULL

	CONSTRAINT PK_REPV_NEMP PRIMARY KEY (NUM_EMPL),
	CONSTRAINT FK_OFC_REPV_OFICR FOREIGN KEY (OFICINA_R) 
	REFERENCES OFICINAS (OFICINA),
	CONSTRAINT FK_REPV_NEMP_DIR FOREIGN KEY (DIRECTOR) 
	REFERENCES REPVENTAS (NUM_EMPL)

	);

alter table oficinas add CONSTRAINT FK_REPV_OFC_DIR FOREIGN KEY (DIR) 
	REFERENCES REPVENTAS(NUM_EMPL);
alter table CLIENTES add CONSTRAINT FK_REPV_CLI_REPC FOREIGN KEY (REP_CLIE) 
	REFERENCES REPVENTAS(NUM_EMPL);
alter table PEDIDOS add CONSTRAINT FK_REPV_PED_REP FOREIGN KEY (REP) 
	REFERENCES REPVENTAS(NUM_EMPL);
